#!/usr/bin/env python3
"""
async_comprehension: Import async_generator from 0-async_generator.py filei
Collects 10 random float values from async_generator.

This coroutine uses an asynchronous comprehension to gather 10 random float
values generated by async_generator. It returns the list of these collected
values without any input arguments.
"""


from typing import List
async_generator = __import__('0-async_generator').async_generator

"""async_comprehension: This coroutine will collect 10 random numbers
using an async comprehensing over async_generator,
then returns the 10 random numbers.
It takes no arguments."""


async def async_comprehension() -> List[float]:
    """Collects 10 random numbers asynchronously using an async comprehension
    over async_generator, then returns these numbers in a list."""
    return [rand_num async for rand_num in async_generator()i]
